### ISSUE TITLE
When using helm-google get an error with the timer

### ISSUE THREAD

**Issue by rustyconover** [steckerhalter/helm-google#14]
Hi, 

When using helm-google and typing a character I receive:

```
Error running timer: (error "In ‘Google’ source: ‘helm-google-search’ 
 (void-variable helm-google-tld)")
```

**Comment by steckerhalter** [comment]
Hi, looks like a bug introduced by the last change to make the search url completely configurable. I'll try to fix it and let you know soon.

**Comment by steckerhalter** [comment]
please try again with the latest version. it should work now

**Comment by rustyconover** [comment]
I still occasionally get transfer interrupted... but that could be the bug
from helm-spotify

http://blog.johnregner.com/post/78877988910/fixing-helm-spotify

**Comment by steckerhalter** [comment]
Ok, I didn't see that. Looks like it could be an Emacs problem (possibly related to the platform?). Are you using the latest version (25.2)? What OS?

**Comment by steckerhalter** [comment]
So I had this issue as well yesterday. I switched to Emacs 25.2 recently from v24. When I was using v24 I didn't have this issue AFAICR.

**Comment by rustyconover** [comment]
I'm using

GNU Emacs 25.2.1 (x86_64-apple-darwin16.4.0, Carbon Version 157 AppKit
1504.81) of 2017-02-20

Build via brew on Mac os X.

**Comment by steckerhalter** [comment]
The Emacs function `url-retrieve-synchronously` seems to get stuck trying to fetch the html (which is also use by `helm-spotify`). Looks like it may be necessary to find an alternative way to fetch the html.

**Comment by steckerhalter** [comment]
I opened an issue for this: https://github.com/steckerhalter/helm-google/issues/15
