### ISSUE TITLE
Choose a browser specific to helm-google

### ISSUE THREAD

**Issue by naclander** [steckerhalter/helm-google#16]
First, thanks for this awesome package.

I would like to open helm-google links in eww, but I don't want this to override opening all links in emacs. For example I still want org links to open in my standard browser. 

Is helm-google able to support choosing a specific browser ( eww, firefox ) just for helm-google results, which can overwrite the `browse-url-browser-function` if set?

**Comment by steckerhalter** [comment]
You're welcome. eww is already bound as an action on <kbd>F2</kbd>

**Comment by naclander** [comment]
Ok, I think that fixes my specific issue.

**Comment by steckerhalter** [comment]
Oh, btw. The actions are customizable through `M-x customize-group RET helm-google RET` or by directly modifying `helm-google-actions`. The default is this:

```cl
(("Browse URL" . browse-url)
 ("Browse URL with EWW" lambda (candidate)
  (eww-browse-url (helm-google-display-to-real candidate))))
```

I can rearrange the actions or add new ones (so for example eww becomes the default).

**Comment by naclander** [comment]
I now have 
``` elisp
(setq helm-google-actions
      '(("Browse URL with EWW" lambda
        (candidate)
        (eww-browse-url
         (helm-google-display-to-real candidate)))
       ("Browse URL" . browse-url)))
```
which does exactly what I want. Thanks.
