### ISSUE TITLE
Missing html2text?

### ISSUE THREAD

**Issue by torgeir** [steckerhalter/helm-google#17]
It's been a while since I used helm-google.. Has `html2text` gone missing? Or is it maybe not part of emacs 25 any longer?

https://github.com/jwiegley/emacs-release/blob/master/lisp/gnus/html2text.el

**Comment by steckerhalter** [comment]
no, it's included and works also in 25.2

**Comment by torgeir** [comment]
Oh, alright, thanks. I wonder whats up on my end then, maybe [it's the fork I'm on](https://github.com/d12frosted/homebrew-emacs-plus)..
