### ISSUE TITLE
html2text obsolete in Emacs 26.1

### ISSUE THREAD

**Issue by Gollum999** [steckerhalter/helm-google#18]
I am getting this error when running `helm-google` with Emacs v26.0.50:

    In ‘Google’ source: ‘helm-google-search’ 
     (void-function html2text)

I think it is related to this commit: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4bd4df40471f42d56e26af9ee62d7a52653ae82a

**Comment by steckerhalter** [comment]
Hmm. Looks like the suggested alternative `shr.el` doesn't contain a similar function. Or at least I couldn't find one yet.

**Comment by steckerhalter** [comment]
I've pushed a change that will use `shr-render-region` if html2text is not available. Please check.
