### ISSUE TITLE
Show the age of pages

### ISSUE THREAD

**Issue by jwiegley** [steckerhalter/helm-google#19]
One thing that helps me identify the page I'm looking for is to see how old it is. This shows up in the Google search results, but not the helm-google results. Would that be possible to add?

**Comment by steckerhalter** [comment]
I think it should be. I'll have a look...

**Comment by steckerhalter** [comment]
So I had look. I couldn't get it to display dates in Emacs. It works in the browser for me with the parameter `&tbs=cdr:1` but no in Emacs:

```cl
(switch-to-buffer (helm-google--response-buffer-from-search "emacs" "https://encrypted.google.com/search?ie=UTF-8&oe=UTF-8&tbs=cdr:1&q=%s"))
```
But in the browser I get dates: https://encrypted.google.com/search?ie=UTF-8&oe=UTF-8&tbs=cdr:1&q=emacs

Hmm... do you get no dates in the Emacs response as well?

**Comment by steckerhalter** [comment]
I tried with eww (and lynx to make sure) as well: no dates returned with the url that works with Firefox (prolly a JS thing?). If you can find out how to get the dates into the response in Emacs, tell me and I can implement the feature. Closing until then... thanks
