### ISSUE TITLE
Can you open a url in EWW instead of external browser?

### ISSUE THREAD

**Issue by LeoUfimtsev** [steckerhalter/helm-google#7]
Hello, 

I love this extension !! 

Just one thing, can it be customized/hacked so that webpages (Opionally) open in eww? 
I.e, some links like reference pages I'd like to open in eww, but others in my usual chrome browser. 

Like e.g:
 <ret> open in Google chrome 
C-<ret> open in eww  

I noticed helm-browse-url-default-browser-alist , ~~but not sure how to use

**Comment by LeoUfimtsev** [comment]
asked about this in S.O
http://stackoverflow.com/questions/28443064/emacs-org-mode-helm-google-open-links-in-eww

**Comment by steckerhalter** [comment]
`helm-google` is using the `browse-url` function:
```cl
(action ("Browse URL" . browse-url))
```

So something like this should work:

```cl
;; define you own browser function (which opens `eww' with the url)
(defun my-browse-url-browser-function (url &rest args)
  (eww url))

;; activate your own browser function
(setq browse-url-browser-function 'my-browse-url-browser-function)
```

**Comment by LeoUfimtsev** [comment]
Thanks, works well!
